import { helpers } from "ytdlp-nodejs";
import { spawn } from "node:child_process";
import dns from "node:dns";
import fs from "node:fs";
import path from "node:path";
import https from "node:https";
import http from "node:http";

// Make Node prefer IPv4 for outbound connections; this helps ensure the
// signed googlevideo URL generated by yt-dlp is requested from the same IP
// family (and therefore the same public IP) as the yt-dlp process that
// produced it, avoiding 403 Forbidden from IP-bound signatures.
dns.setDefaultResultOrder("ipv4first");

export const config = {
  api: {
    responseLimit: false,
  },
};

const YTDLP_PATH = process.env.YTDLP_PATH || helpers.findYtdlpBinary();

let cookieFileWritten = false;
function cookieFilePath() {
  if (!process.env.YOUTUBE_COOKIES) return null;
  if (cookieFileWritten) return "/tmp/youtube_cookies.txt";
  fs.writeFileSync("/tmp/youtube_cookies.txt", process.env.YOUTUBE_COOKIES, "utf8");
  cookieFileWritten = true;
  return "/tmp/youtube_cookies.txt";
}

function baseYtDlpArgs() {
  const args = ["--no-warnings", "--no-update", "--no-cache-dir", "--force-ipv4", "--js-runtimes", "node"];
  if (process.env.YTDLP_PROXY) args.push("--proxy", process.env.YTDLP_PROXY);
  if (process.env.YTDLP_EXTRACTOR_ARGS) args.push("--extractor-args", process.env.YTDLP_EXTRACTOR_ARGS);
  const cookies = cookieFilePath();
  if (cookies) args.push("--cookies", cookies);
  return args;
}

function binaryCandidates() {
  return [
    YTDLP_PATH,
    path.resolve("node_modules/ytdlp-nodejs/bin/yt-dlp"),
    path.resolve("vercel-backend/node_modules/ytdlp-nodejs/bin/yt-dlp"),
    "/tmp/yt-dlp",
  ].filter(Boolean);
}

function findExistingBinary() {
  for (const p of binaryCandidates()) {
    if (p && fs.existsSync(p)) return p;
  }
  return null;
}

function assetNameForRuntime() {
  const { platform, arch } = process;
  if (platform === "linux") {
    if (arch === "x64") return "yt-dlp_linux";
    if (arch === "arm64" || arch === "aarch64") return "yt-dlp_linux_aarch64";
    if (arch === "armv7l") return "yt-dlp_linux_armv7l";
  }
  if (platform === "darwin") {
    return "yt-dlp_macos";
  }
  if (platform === "win32") {
    if (arch === "x64") return "yt-dlp.exe";
    if (arch === "arm64") return "yt-dlp_arm64.exe";
    if (arch === "ia32") return "yt-dlp_x86.exe";
  }
  if (platform === "android" && arch === "arm64") {
    return "yt-dlp_linux_aarch64";
  }
  return null;
}

function downloadFile(url, dest) {
  return new Promise((resolve, reject) => {
    const mod = url.startsWith("https:") ? https : http;
    const req = mod.get(url, (res) => {
      if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
        downloadFile(new URL(res.headers.location, url).toString(), dest)
          .then(resolve)
          .catch(reject);
        return;
      }
      if (res.statusCode !== 200) {
        reject(new Error(`Failed to download ${url}: ${res.statusCode} ${res.statusMessage}`));
        return;
      }
      const file = fs.createWriteStream(dest);
      res.pipe(file);
      file.on("finish", () => {
        file.close();
        resolve();
      });
      file.on("error", reject);
      res.on("error", reject);
    });
    req.on("error", reject);
    req.setTimeout(120000, () => {
      req.destroy();
      reject(new Error("Download timed out"));
    });
  });
}

async function ensureStandaloneBinary() {
  const asset = assetNameForRuntime();
  if (!asset) {
    throw new Error(`No standalone yt-dlp binary available for ${process.platform} ${process.arch}`);
  }

  const tmpDir = process.env.TMPDIR || "/tmp";
  const dest = path.join(tmpDir, "yt-dlp");

  if (fs.existsSync(dest)) {
    try {
      fs.accessSync(dest, fs.constants.X_OK);
      return dest;
    } catch {
      fs.unlinkSync(dest);
    }
  }

  const url = `https://github.com/yt-dlp/yt-dlp/releases/latest/download/${asset}`;
  console.log("[stream] Downloading standalone yt-dlp from", url);
  await downloadFile(url, `${dest}.tmp`);
  fs.renameSync(`${dest}.tmp`, dest);
  if (process.platform !== "win32") {
    fs.chmodSync(dest, 0o755);
  }
  console.log("[stream] Standalone yt-dlp saved to", dest);
  return dest;
}

async function getYtDlpBinary() {
  const existing = findExistingBinary();
  if (existing) return existing;
  return ensureStandaloneBinary();
}

function spawnYtDlp(binaryPath, extraArgs) {
  return spawn(binaryPath, [
    ...baseYtDlpArgs(),
    ...extraArgs,
  ], { stdio: ["ignore", "pipe", "pipe"], env: { ...process.env, PATH: `${process.env.PATH}:${path.dirname(process.execPath)}` } });
}

async function getInfo(binaryPath, youtubeUrl) {
  const proc = spawnYtDlp(binaryPath, [
    "--dump-json",
    "--extractor-retries", "2",
    youtubeUrl,
  ]);

  return new Promise((resolve, reject) => {
    let stdout = "";
    let stderr = "";

    proc.stdout.setEncoding("utf8");
    proc.stdout.on("data", (chunk) => { stdout += chunk; });

    proc.stderr.setEncoding("utf8");
    proc.stderr.on("data", (chunk) => { stderr += chunk; });

    proc.on("error", reject);
    proc.on("close", (code) => {
      if (code !== 0) {
        return reject(new Error(`yt-dlp exited with code ${code}: ${stderr.trim() || "Unknown yt-dlp error"}`));
      }
      try {
        const info = JSON.parse(stdout);
        resolve(info);
      } catch (e) {
        reject(new Error(`Failed to parse yt-dlp output: ${e.message}`));
      }
    });
  });
}

function isAudioFormat(format) {
  return format.vcodec === "none" || format.resolution === "audio only";
}

function preferAudioFormat(formats) {
  const audio = (formats || [])
    .filter(isAudioFormat)
    .sort((a, b) => (b.abr || 0) - (a.abr || 0));

  if (!audio.length) return formats || [];

  const m4aLike = audio.find(
    (f) =>
      f.ext === "m4a" ||
      f.acodec?.includes("mp4a") ||
      f.acodec?.includes("aac")
  );

  return m4aLike ? [m4aLike] : audio;
}

function contentTypeFor(format) {
  const ext = format.ext;
  if (ext === "m4a" || ext === "mp4") return "audio/mp4";
  if (ext === "webm") return "audio/webm";
  if (ext === "mp3") return "audio/mpeg";
  if (ext === "ogg") return "audio/ogg";
  return format.vcodec === "none" ? "audio/mpeg" : "video/mp4";
}

function sendError(res, status, obj) {
  const body = JSON.stringify(obj);
  res.statusCode = status;
  res.setHeader("Content-Type", "application/json");
  res.setHeader("Content-Length", Buffer.byteLength(body));
  res.end(body);
}

function streamFromYtdlp(binaryPath, info, youtubeUrl, res, videoId) {
  const format = preferAudioFormat(info.formats || [])[0];
  if (!format) {
    if (!res.headersSent) sendError(res, 404, { error: "No audio formats" });
    return Promise.resolve();
  }

  const contentType = contentTypeFor(format);

  res.statusCode = 200;
  res.setHeader("Content-Type", contentType);
  if (format.filesize) {
    res.setHeader("Content-Length", String(format.filesize));
  }
  res.setHeader("Accept-Ranges", "bytes");
  res.setHeader("Cache-Control", "public, max-age=86400");
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Headers", "Range, Accept, Authorization");
  res.setHeader("Access-Control-Expose-Headers", "Content-Range, Content-Length, Accept-Ranges");

  // Dump the extracted info so yt-dlp can download without re-hitting YouTube
  const infoPath = `/tmp/info-${videoId}.json`;
  try {
    fs.writeFileSync(infoPath, JSON.stringify(info));
  } catch (e) {
    console.error("[stream] failed to write info json:", e.message);
  }

  const args = [
    "--load-info-json",
    infoPath,
    "-f",
    String(format.format_id),
    "--no-part",
    "-o",
    "-",
    youtubeUrl,
  ];
  const proc = spawnYtDlp(binaryPath, args);
  console.log("[stream] Spawning yt-dlp for direct download, format:", format.format_id);

  proc.stdout.pipe(res);

  let stderrBuf = "";
  proc.stderr.on("data", (chunk) => {
    stderrBuf += chunk.toString();
    const lines = stderrBuf.split("\n");
    stderrBuf = lines.pop();
    for (const line of lines) {
      if (line.trim()) console.log("[yt-dlp]", line.trim());
    }
  });

  return new Promise((resolve, reject) => {
    proc.on("error", (err) => {
      console.error("[stream] yt-dlp spawn error:", err);
      if (!res.headersSent) {
        sendError(res, 500, { error: "yt-dlp spawn failed", details: err.message });
      } else if (!res.destroyed && !res.writableEnded) {
        try { res.end(); } catch {}
      }
      reject(err);
    });

    proc.on("close", (code) => {
      if (code !== 0) {
        console.error("[stream] yt-dlp exited with code", code);
        if (!res.headersSent) {
          sendError(res, 500, { error: "yt-dlp exited with code", details: String(code) });
        } else if (!res.destroyed && !res.writableEnded) {
          try { res.end(); } catch {}
        }
        reject(new Error(`yt-dlp exited with code ${code}`));
      } else {
        resolve();
      }
    });
  });
}

export default async function handler(req, res) {
  // CORS preflight for cross-origin <audio> / Service Worker requests
  if (req.method === "OPTIONS") {
    res.statusCode = 204;
    res.setHeader("Access-Control-Allow-Origin", "*");
    res.setHeader("Access-Control-Allow-Methods", "GET, HEAD, OPTIONS");
    res.setHeader("Access-Control-Allow-Headers", "Range, Accept, Authorization, Content-Type");
    res.setHeader("Access-Control-Expose-Headers", "Content-Range, Content-Length, Accept-Ranges");
    res.setHeader("Access-Control-Max-Age", "86400");
    return res.end();
  }

  try {
    const videoId = req.query.v;

    if (!videoId || typeof videoId !== "string" || videoId.length > 20) {
      return sendError(res, 400, { error: "Missing or invalid video ID parameter (v)" });
    }

    const youtubeUrl = `https://www.youtube.com/watch?v=${videoId}`;
    console.log("[stream] Starting for:", videoId);

    let binaryPath = await getYtDlpBinary();
    let info;
    try {
      info = await getInfo(binaryPath, youtubeUrl);
    } catch (err) {
      console.warn("[stream] yt-dlp info failed, trying standalone binary:", err.message);
      binaryPath = await ensureStandaloneBinary();
      info = await getInfo(binaryPath, youtubeUrl);
    }

    const format = preferAudioFormat(info.formats || [])[0];
    console.log("[stream] Using format:", format?.format_id, format?.ext, format?.acodec, format?.abr);

    await streamFromYtdlp(binaryPath, info, youtubeUrl, res, videoId);
  } catch (err) {
    console.error("[stream] FATAL:", err);
    if (!res.headersSent) {
      return sendError(res, 500, { error: "Internal error", details: err.message });
    }
  }
}
